### ISSUE TITLE
Constrained bytes in files vs. bytes in symbolic variables difference

### ISSUE THREAD

**Issue by juk80x** [angr/claripy#10]
When a byte in a file is constrained the bit index in the constraint starts at 0, e.g. file[7:0] for the first byte of the file. When a byte in a variable is constrained the bit index starts at VARIABLE_LENGTH-1, e.g. arg[39:32] for a variable that is 40 bits long. This appears to be a recent change. 

I have code that attempts to answer the question is byte X in file/arg constrained. It would help if there was some consistency in how bytes are represented as constraints.

**Comment by rhelmot** [comment]
It's possible what you're seeing is because of endianness? There have been no changes to this behavior in a very long time. 

[7:0] always refers to the least significant byte in the number, and symbolic variables for un constrained input data are usually represented in big endian format.

**Comment by zardus** [comment]
Are you still running into this? If so, could you create a failing testcase so that we can recreate the issue? The process to do that is described [here](http://docs.angr.io/HACKING.html).
