### ISSUE TITLE
STP backend for Claripy

### ISSUE THREAD

**Issue by steseb** [angr/claripy#122]
Hi,
I'm trying to write a Claripy Backend for STP. I'm able to register the new backend by
`_backend_manager.backends._register_backend`

but when I create a new BVS or BVV, Claripy always calls the Z3 Backend. How can I select the backend that I would like to use?

Thank you

**Comment by zardus** [comment]
Does claripy call it on BVS creation, or when you add or solve? If it's the latter, you'll need to create your `Solver` with the right `backend` argument (see the default in solvers.py).

**Comment by steseb** [comment]
Ok thanks it actually calls z3 on the eval. And as you suggested, creating the solver as:
`claripy.Solver(backend=backends.stp)`
will invoke the STP solver on the eval.
