### ISSUE TITLE
Claripy right shift incorrect

### ISSUE THREAD

**Issue by thomasbrandon** [angr/claripy#127]
The claripy right shift operator (`>>`/`__rshift__`) is incorrect in certain cases (and doesn't seem to reflect any sort of shift/rotate). Looks like when the highest bit is set it fills it down.
For instance:
```
In [57]: claripy.BVV(0x80, 8) >> 3
Out[57]: <BV8 240>
```
claripy.LShR is correct:
```
In [4]: claripy.LShR(BVV(0x80,8),3)
Out[4]: <BV8 16>
```
The left shift operator seems fine.

Tested with 8.19.2.4 (and a couple of older versions).

**Comment by rhelmot** [comment]
This is called "arithmetic shift". It treats the number as a signed value. To do an unsigned shift, you want "logical shit", the LShR operator, which you seem to have found just fine.

Trust us, if right shift really didn't work we would have figured it out a lot sooner :P
