### ISSUE TITLE
a check is added to disrupt the z3 backend

### ISSUE THREAD

**Issue by ww9210** [angr/claripy#137]
In the  backends/backend_z3.py, the function _add() has a check added recently to avoids to add some already seen constraints(?), which seems to me, does not make much sense, and causes abnormal behavior like generating conflicting constraints, I believe this is the root cause of https://github.com/angr/angr/issues/1517.
simply remove this check should fix this issue.

```
   def _add(self, s, c, track=False):
        if track:
            for constraint in c:
                name = str(hash(constraint))
                if name not in self._hash_to_constraint: // why is this line added?
                    self._hash_to_constraint[name] = constraint
                    s.assert_and_track(constraint, name)
        else:
            s.add(*c)
```

**Comment by rhelmot** [comment]
@Lukas-Dresel and @Phat3 were discussing this internally yesterday. It's blocking some internal work too, so expect a fix soon.

**Comment by Lukas-Dresel** [comment]
@ww9210 we were discussing what the right way to fix this is, i have a fix that i have not pushed yet. I will push it very soon, aka sometime today.

**Comment by Phat3** [comment]
I added that check to fix a bug when using the option `reuse_z3_solver` with the new version of z3 (`4.8.5`, currently not supported by angr). 

In the newer version of z3 if you try to assert the same constraint multiple times the solver throws an exception while in the older version of z3 (the one that angr is using) this behavior is perfectly fine.

After discussing with @Lukas-Dresel we agreed that the correct fix would be to clear the attribute `_hash_to_constraint` everytime the solver is recreated and remove the buggy line in `_add`

**Comment by Lukas-Dresel** [comment]
@ww9210 Just pushed the commit, should hopefully be fixed now. The mapping should not persist between solver recreations.
