### ISSUE TITLE
Need a concept of operator precedence in claripy op rendering

### ISSUE THREAD

**Issue by rhelmot** [angr/claripy#141]
It would be nice to extend the way `Base._op_repr` worked to make it so that it put parentheses only where they needed to go.

**Comment by saullocarvalho** [comment]
I am interested in helping. What can I do?

**Comment by rhelmot** [comment]
So we need:

- add some sort of mapping in claripy from op string which has a symbol associated (e.g. `__add__` has the + symbol associated) to precedence level, and some understanding of the associativity of each level, a la https://en.cppreference.com/w/c/language/operator_precedence
- change the ast repr process so that it only adds parentheses around an operation if its parent operation is of a higher (smaller number in the linked chart) precedence or if it violates the associativity rules
- tests

The ast repr process is currently a dizzyingly complicated iterated algorithm instead of a recursive algorithm because at one point someone contributed a change switching all our recursive AST processing code into iterated stack-based algorithms. I would be okay if you rewrote the AST rendering algorithm from the ground up as a recursive algorithm again; I could do the conversion to the iterated form myself.
