### ISSUE TITLE
Satisfiability bug with CompositeFrontend

### ISSUE THREAD

**Issue by palkeo** [angr/claripy#16]
Hello !

I have found a sequence of step that makes the CompositeFrontend return invalid satisfiability.

I will just drop you the script to reproduce the issue :

```
import claripy

full_frontend = claripy.FullFrontend(claripy.backends.z3)
s =  claripy.CompositeFrontend(full_frontend)

#s = claripy.Solver()

c = claripy.BVS('test', 32)
s.add(c[7:0] != 0)

print(s.satisfiable())

s.add(c == 0)

s.satisfiable(extra_constraints=[claripy.BVS('lol', 32)==0])

print(s.satisfiable())
```

You can see that at the end, the constraints are clearly not satisfiable (c must be null but not null), but my satisfiable() call with extra_constraints containing another variable seems to confuse the CompositeFrontend.

If you remove that satisfiable(extra_constraints=...), or if you use the default claripy.Solver(), the bug will not appear.

Thanks :)

**Comment by zardus** [comment]
I tracked the issue down! The fix is:

```diff
diff --git a/claripy/frontends/composite_frontend.py b/claripy/frontends/composite_frontend.py
index 2a51a67..ec5b739 100644
--- a/claripy/frontends/composite_frontend.py
+++ b/claripy/frontends/composite_frontend.py
@@ -161,7 +161,7 @@ class CompositeFrontend(ConstrainedFrontend):
             extra_vars = frozenset.union(*(a.variables for a in extra_constraints))
             solvers = [ self._merged_solver_for(extra_vars) ]
             for s in self._solver_list:
-                if len(s.variables | solvers[0].variables) == 0:
+                if s.variables.isdisjoint(solvers[0].variables):
                     solvers.append(s)
         else:
             solvers = self._solver_list
```

I was using `|` instead of `&`, and the result was then cached.

We're currently have a bit of a merge situation in claripy, so it might take be a little bit to push the fix. I'll close this issue when I push it.

Thank you for finding this bug!

**Comment by palkeo** [comment]
Cool, thanks !

**Comment by palkeo** [comment]
I'm pretty sure that this bug is still here, maybe in a more complex form:
I applied your patch, and I have the solver that returns that something is satisfiable when it should probably not. If I do the exact same thing by branching the solver and adding the same constraints, it's not satisfiable.
I can't give you an example, because it's on fairly complex real-world data (quite hard to interpret).

But maybe you should take a second look if you have time. Or I will try to help when I will have time :)

**Comment by zardus** [comment]
github seems to have eaten your last comment, but I've now gone and basically rewritten the entire composite frontend. As soon as I can get this stuff merged in, it'd be great to check if it fixes your issue!

**Comment by zardus** [comment]
Okay, here we go! The new `claripy.CompositeSolver` just made its debut. It's improved over the old `CompositeFrontend` in almost every way, and is fast and reliable enough for us to have just made it the default solver in SimuVEX. Thanks for tracking down these bugs, and me know if you find any more issues with it!

**Comment by palkeo** [comment]
Awesome, I will test that, then :)
