### ISSUE TITLE
Missed easy simplification opportunity?

### ISSUE THREAD

**Issue by edmcman** [angr/claripy#163]
I have a rather complicated symbolic expression:

```
In [70]: sttest.regs.rbx                                                                                                                                                                     
Out[70]: <BV64 ((if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 190)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 180)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 222)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 192)))))))))) .. 0x0 .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then loadme_55_8 else 0))))))))) + stack2_59_64>
```

If I concretize it:

```
In [72]: hex(sttest.solver.eval(stack1))                                                                                                                                                         
Out[72]: '0x601006'

In [74]: sttest.add_constraints(stack1 == 0x601006)                                                                                                                                          

In [75]: sttest.WARNING | 2020-02-07 15:26:50,783 | angr.state_plugins.abstract_memory | Option "REGION_MAPPING" must be enabled when using SimAbstractMemory as the memory model. The option is added to state options as a courtesy.
CRITICAL | 2020-02-07 15:26:50,813 | angr.sim_state | The name state.se is deprecated; please use state.solver.
In [75]: sttest.satisfiable()                                                                                                                                                                
Out[75]: True

In [76]: sttest.regs.rbx                                                                                                                                                                     
Out[76]: <BV64 ((if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 190)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 180)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 222)))))))))) .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then 0 else (if stack1_58_64 == 0x601009 then 0 else (if stack1_58_64 == 0x601008 then 0 else 192)))))))))) .. 0x0 .. (if stack1_58_64 == 0x60100d then 0 else (if stack1_58_64 == 0x601007 then 0 else (if stack1_58_64 == 0x60100c then 0 else (if stack1_58_64 == 0x601006 then 0 else (if stack1_58_64 == 0x60100b then 0 else (if stack1_58_64 == 0x601005 then 0 else (if stack1_58_64 == 0x60100a then 0 else (if stack1_58_64 == 0x601004 then loadme_55_8 else 0))))))))) + stack2_59_64>
```

So after concretizing stack1 the complicated expression based on it is not simplified.

Indeed:

```
In [81]: sttest.solver.is_true(stack1 == 0x60100d)                                                                                                                                           
Out[81]: False
```

Am I doing something wrong?  Is there a better way to concretize a symbolic variable to concrete bitvector so that simplifications can happen?

**Comment by rhelmot** [comment]
to put it simply, that's not how symbolic expressions work and it's not how they _should_ work for a variety of applications.

Notably, ASTs are _immutable_, meaning nothing about their structure changes, ever.
After that, there is no way to enumerate all storage locations in a state, and if there were, it would be prohibitively expensive. The thing you're asking for is effectively that after you add that constraint, we crawl through literally every single storage location and try to see if it can be simplified with respect to that constraint. That's very silly.

I don't know if this is what you're looking for, but angr supports something called the "replacement solver", which allows you to add replacements (like `stack1 -> 0x601006`) and have them automatically applied at solve time (including `is_true`, iirc?). You can enable it by adding the `REPLACEMENT_SOLVER` option at state construction time.

**Comment by edmcman** [comment]
I agree: the solver obviously cannot simplify existing expressions if they are immutable.

But I disagree that it's impractical for SimState to apply such simplifications over all expressions it is responsible for.  Assuming that you are using hash consing, such an operation would be O(number of _unique_ symbolic expressions created), which is generally not that large.  This is what Mayhem does when it concretizes a symbolic expression FTR.  It can drastically simplify expressions that result from symbolic memory reads and writes.

In either case, it seems that if someone _explicitly_ requests to simplify an expression that includes an expression e, and there is a constraint e=n where n is a bitvector constant, doesn't it make sense to substitute instances of e with n?  I forgot to include that in my original question, but I did explicitly call `simplify` on the symbolic expression of rbx and it did not make this simplification.

Anyway, there were two purposes two my question.  One was to find out if there is an angr way of concretizing an expression and simplifying the resulting state.  It sounds like the answer is no, but maybe the replacement solver can be used for this.  I'll look into that.  Thank you for pointing that out to me.  In either case, it won't be hard to implement it.

The second purpose of my question was to understand if there is an opportunity for improvement.  If I'm going to have to implement the simplification, I'd rather do it on the angr side and submit it as a pull request so people don't have to reinvent the wheel.  Specifically, I think this could just be a claripy simplification that does the e=n substitution described above.  If that sounds reasonable, I will make a separate feature request and can work on a PR.  If not, I'll just implement the functionality I need in my application.

**Comment by ShadowLL** [comment]
Hello, I noticed that when this type of expression <a + b-b> appears, angr does not simplify it to expression <a>. Is this the same type of problem as the one you described? In addition, please tell me if you have any feasible solutions or ideas now?

**Comment by rhelmot** [comment]
No, the simplification you're talking about is actually reasonable to implement, and would be found in [claripy/simplifications.py](https://github.com/angr/claripy/blob/master/claripy/simplifications.py).

**Comment by ShadowLL** [comment]
@rhelmot Thank you very much for your quick response.

**Comment by rhelmot** [comment]
the thing you want is sort of already implemented in the `bitwise_sub_simplifier`, but the cases it tries to address are when one of a or b is concrete. It could be changed so that it checks the weight of the tree to see if it is actually doing a reasonable "balance", or it could be changed to explicitly cater to your case of trying to perform an elimination.

**Comment by rhelmot** [comment]
@zardus promised he would answer the original question in this thread, and he has since flaked on this promise like three or four times, so 1) this is a callout for him being a shitty maintainer and bad at keeping promises, and 2) my attempt to explain why we don't support full-state replacement operations.

Basically, this would mean that every single state plugin would need to support a `replace` operation, since every state plugin can contain, well, state. We want the state plugin interface to be as light as possible in order to make it easy to implement new plugins. This interface would also heavily tie state plugins to the claripy data types, which is not desirable. I guess you could define replace as an operation over other kinds of data but it would be sketchy and would be using claripy as a point of reference.

If you want to submit a PR which adds `replace` to every single state plugin, be my guest, but you may find that there is a lot more nuance here than you expect. For example, you will need to do the same `memo` trick as `copy` does in order to not do replacement twice when two references to the same plugin-like object are stored, as is common in the filesystem.

**Comment by ShadowLL** [comment]
@rhelmot Thanks for your explanation. I want to use symbolic execution to solve problems like z = x + y, d = z-x in the stain propagation process, but d in the statement has nothing to do with x, but I encountered the above difficulties in trying to simplify the symbolic expression.

**Comment by edmcman** [comment]
> @zardus promised he would answer the original question in this thread, and he has since flaked on this promise like three or four times, so 1) this is a callout for him being a shitty maintainer and bad at keeping promises, and 2) my attempt to explain why we don't support full-state replacement operations.

:rofl: 

> Basically, this would mean that every single state plugin would need to support a replace operation, since every state plugin can contain, well, state. We want the state plugin interface to be as light as possible in order to make it easy to implement new plugins. This interface would also heavily tie state plugins to the claripy data types, which is not desirable. I guess you could define replace as an operation over other kinds of data but it would be sketchy and would be using claripy as a point of reference.

> If you want to submit a PR which adds replace to every single state plugin, be my guest, but you may find that there is a lot more nuance here than you expect. For example, you will need to do the same memo trick as copy does in order to not do replacement twice when two references to the same plugin-like object are stored, as is common in the filesystem.

I ended up solving my original problem in a completely different way, so I'm not quite as personally invested in this anymore... but I still think it's an interesting topic.  Your rationale seems perfectly reasonable for why there is not a full-state replacement operation, and I'm not dying to write a PR for every state plugin :)

Maybe there is still value in doing the context-specific simplification without replacing all the existing state.   It could still be applied to newly created expressions, or on demand, which would have solved my original problem.

**Comment by rhelmot** [comment]
"On demand" is effectively what the replacement solver does.

**Comment by edmcman** [comment]
Good point.  I forgot about the replacement solver.  I will close this issue.

**Comment by zardus** [comment]
As an aside, we actually support this and have done so since almost the very beginning of angr's history. This is how our static analysis handles narrowing and widening.

Example usage, during static analysis: https://github.com/angr/angr/blob/master/angr/sim_state.py#L490
The implementation: https://github.com/angr/angr/blob/master/angr/storage/paged_memory.py#L809

This implementation has only really been used statically, as opposed to during DSE, but from a glance at the code, it should work. It's also just implemented for memory regions, but I guess that'd typically be a) the hard part and b) the common use-case anyways.

It also won't be very fast. From that perspective, the replacement solver is better.
