### ISSUE TITLE
Does Claripy cache function summaries?

### ISSUE THREAD

**Issue by behnamben** [angr/claripy#165]
While claripy solves the constraint values , does it cache the results for future use in program analysis? 
maybe we have a function that is used many times, and we dont need to calculate its constraints each time we see the function.

**Comment by zardus** [comment]
The only caching we currently do is caching the solutions for specific sets of constraints (here: https://github.com/angr/claripy/blob/master/claripy/frontend_mixins/model_cache_mixin.py). This is much basic than the type of caching that you're talking about. The reason the caching you're talking about is hard to do is that the behavior of a given function generally varies widely based on the data passed in (in the symbolic case, based on the symbolicity and constraints of that data), and its state effects and resulting constraints will vary widely with that behavior. Caching that is quite challenge. We *do* have some ongoing research work to address this issue, but nothing that's really ready for use.
