### ISSUE TITLE
How to update a bv?

### ISSUE THREAD

**Issue by tomoarrow** [angr/claripy#166]
suppose there is a `<BV32 (x_1_32 + y_2_32) - z_3_32>` , I want to update `x` to `0x1` , `y` to `0x2` and `z` to `m`. Is there a way to get `<BV32 0x3 - m_4_32>` directly?  or I can only update the ast recursively?

**Comment by zardus** [comment]
Please check the API docs for this sort of thing:

http://angr.io/api-doc/claripy.html#claripy.ast.base.Base.replace and http://angr.io/api-doc/claripy.html#claripy.ast.base.Base.replace_dict
