### ISSUE TITLE
Is division signed or unsigned ?

### ISSUE THREAD

**Issue by palkeo** [angr/claripy#18]
If I create these variables :
a = claripy.BVV(5, 8)
b = claripy.BVV(254, 8)

Then, "a / b" is zero. So it's like the division is unsigned.

However, if now I set b to be a claripy.BVS('denominator', 8)
Then I instantiate a claripy.Solver, add a constraint that "a / b > 10" and that "b > 0", it is satisfiable, and it tells me that it works with b being 254.

So, I suppose this is not coherent.
Maybe you could make it more explicit, and you could also support both signed/unsigned divisions ?

Thanks !

**Comment by salls** [comment]
Thanks for the bug report! The signedness of division was definitely broken.
In commit https://github.com/angr/claripy/commit/54552b5e8d681cc546332170672561b261980909 I fixed it so that `__div__` is always unsigned.
I also added `SDiv` and `SMod` to support signed division and signed remainder.

**Comment by palkeo** [comment]
Yay, thanks a lot :)
