### ISSUE TITLE
solving constraint with initial value

### ISSUE THREAD

**Issue by bejab2020** [angr/claripy#223]
hi 

is there an ability that I can offer to solver some initial value then solver solves the constraints base on this value?

for example :
s=claripy.Solver()
x=claripy.BVS('x',64)
s.add(x.chop(8)[-1] == 'a')

i have <Bool x_0_64[7:0] == 97> constraint then i give the solver this claripy.BVV('Assfdsss') initial value and solver base on this initial value solves the constraint (i mean it just change the first character to satisfy this constraint no other ones).

thanks

**Comment by rhelmot** [comment]
The thing you want to do is not something supported by z3 I believe. If you can find a constraint solve which supports this kind of operation we will gladly integrate it into claripy.

**Comment by bejab2020** [comment]
thanks for the response if we want to check that a value is a solution for our constraints, we use the solution function, but if our constraints, contain many variable and we have sample values for all of them, then we want to check that the combination of these values is the solution for our constraints, is there any way that we can do this (I search a lot but I didn't find any solution) for example:

s=claripy.Solver()
x=claripy.BVS('x',32)
y=claripy.BVS('y',32)
s.add(x+y < 10)
s.add(x>5)
s.add(y<8)

an_x=claripy.BVV(6,32)
an_y=claripy.BVV(6,32)

s.solution(y,an_y)//True
s.solution(x,an_x)//True


the solver return true for the each of them but the combination of these two value are not the solution.

**Comment by bejab2020** [comment]
thanks for the response if we want to check that a value is a solution for our constraints, we use the solution function, but if our constraints, contain many variable and we have sample values for all of them, then we want to check that the combination of these values is the solution for our constraints, is there any way that we can do this? (I search a lot but I didn't find any solution) for example:

s=claripy.Solver()
x=claripy.BVS('x',32)
y=claripy.BVS('y',32)
s.add(x+y < 10)
s.add(x>5)
s.add(y<8)

an_x=claripy.BVV(6,32)
an_y=claripy.BVV(6,32)

s.solution(y,an_y)//True
s.solution(x,an_x)//True

the solver returns true for each of them but the combination of these two values is not the solution.

**Comment by rhelmot** [comment]
`solution(x, y)` is just a shorthand for `satisfiable(extra_constraints=(x == y,))`, so you can do `s.satisfiable(extra_constraints=(y == an_y, x == an_x))`.
