### ISSUE TITLE
Endless loop in claripy

### ISSUE THREAD

**Issue by axt** [angr/claripy#23]
Hi! I've got this stacktrace while doing a VFG. This is with the current HEAD (235a7a9) version, so the line numbers should be correct.

Should I submit my binary and the code running the VFG?
Or should I try to create a simplified testcase for this?

```
Traceback (most recent call last):
  File "vfg.py", line 1227, in _get_simrun
    sim_run = self.project.factory.sim_run(current_path.state, jumpkind=jumpkind, num_inst=num_inst)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 173, in sim_run
    r = self.sim_block(state, addr=addr, **block_opts)
  File "/usr/local/lib/python2.7/dist-packages/angr/factory.py", line 95, in sim_block
    force_bbl_addr=force_bbl_addr)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/vex/irsb.py", line 69, in __init__
    self._handle_irsb()
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/vex/irsb.py", line 102, in _handle_irsb
    self._handle_statements()
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/vex/irsb.py", line 248, in _handle_statements
    e = self.add_successor(self.state.copy(), s_stmt.target, s_stmt.guard, s_stmt.jumpkind, stmt_idx)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/s_run.py", line 100, in add_successor
    state.add_constraints(guard)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/s_state.py", line 294, in add_constraints
    if self.se.is_false(arg):
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/plugins/solver.py", line 135, in concrete_shortcut_not_bool
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/s_action_object.py", line 53, in ast_stripper
    return f(*new_args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/plugins/solver.py", line 86, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simuvex-5.6.8.22-py2.7.egg/simuvex/plugins/solver.py", line 421, in is_false
    return self._solver.is_false(e, extra_constraints=self._adjust_constraint_list(extra_constraints), exact=exact)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/concrete_handler_mixin.py", line 60, in is_false
    return super(ConcreteHandlerMixin, self).is_false(e, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 61, in is_false
    return super(ConstraintFilterMixin, self).is_false(e, extra_constraints=ec, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontends/light_frontend.py", line 77, in is_false
    return self._solver_backend.is_false(e)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 291, in is_false
    f = self._is_false(self.convert(e), extra_constraints=extra_constraints, solver=solver, model_callback=model_callback)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 96, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 161, in convert
    r = self.call(expr.op, expr.args)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 195, in call
    converted = self.convert_list(args)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 183, in convert_list
    return [ self.convert(a) for a in args ]
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 96, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 161, in convert
    r = self.call(expr.op, expr.args)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 195, in call
    converted = self.convert_list(args)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 183, in convert_list
    return [ self.convert(a) for a in args ]
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 96, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 158, in convert
    r = self._op_expr[expr.op](expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 43, in converter
    raw_args[i] = self.convert(raw_args[i])
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 96, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 158, in convert
    r = self._op_expr[expr.op](expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 43, in converter
    raw_args[i] = self.convert(raw_args[i])
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/backend_vsa.py", line 96, in convert
    return Backend.convert(self, expr.ite_excavated if isinstance(expr, Base) else expr)
  File "/usr/local/lib/python2.7/dist-packages/claripy/backends/__init__.py", line 158, in convert
```

**Comment by axt** [comment]
An update on the previous:

At `backend_vsa:43`, I've tried to print `raw_args`. Printing in simply with `print` causes an endless loop, so I've tried to rever its structure manually. It contains something like this:
```
union
    union
        union
            union
                union
                    union
                        union
                            union
                                union
                                    union
                                        union
                                            union
                                                union
                                                    union  
                                                        union
                                                            union
                                                                union
                                                                    x
                                                                    0xce000000
                                                                0x12
                                                            0x1200
                                                        0x12000b
                                                    0x12000b00
                                                0xb0017
                                            0xb00170c
                                        0x170c00
                                    0x170c0000
                                0xc0000020
                            0x2061
                        0x206100
                    0x20610000
                0x61000020
            0x2000
        0x200000
    0x20000000
```

**Comment by ltfish** [comment]
Give me the binary. I'm taking this weekend off, so I can only take a look at this issue on Monday.

**Comment by axt** [comment]
Attached it with along with the code that triggers the problem:
[testcase.zip](https://github.com/angr/claripy/files/465778/testcase.zip)

**Comment by axt** [comment]
Also have a bit unrelated question. When I run it, it also creates the following warnings:

```
WARNING | 2016-09-11 04:25:50,790 | claripy.vsa.strided_interval | Reversing a real strided-interval <32>0x1[0xffff8000, 0x7fff]R is bad
WARNING | 2016-09-11 04:25:50,791 | claripy.vsa.strided_interval | Tried to cast_low an interval to a an interval shorter than its stride.
WARNING | 2016-09-11 04:25:50,812 | claripy.vsa.strided_interval | Reversing a real strided-interval <16>0x1[0x80, 0x7fff]R is bad
WARNING | 2016-09-11 04:25:50,813 | claripy.vsa.strided_interval | Reversing a real strided-interval <16>0x1[0x80, 0x7fff]R is bad
```

They are most probably caused, by expression like these:
```
SignExt(16,Reverse(Extract(31, 16,Reverse(SignExt(16,BVS)))))
```

I came up with this https://github.com/axt/angr-utils/blob/master/angrutils/inspect.py, to  simplify this type of expressions, when running pathgroup exploration, although specifying it for VFG initial_state, it does not do anything. Probably my callbacks are not called, because of running in mode 'static', but didn't checked this deeper.

Question: Couldn't we add this kind of simplification at claripy level generally?

**Comment by axt** [comment]
Here is a simplified example to trigger the bug:

```
    bname = "1.6.26-libjsound.so"    
    project = angr.Project(bname, load_options={'auto_load_libs':False, 'main_opts': {'custom_base_addr': 0x0}})
    initial_state = project.factory.blank_state(mode="static")
    initial_state.ip = 0x1331b
    sim_run = project.factory.sim_run(initial_state, jumpkind='Ijk_Boring', num_inst=3)
```

**Comment by axt** [comment]
Also if I add `AVOID_MULTIVALUED_READS` and `AVOID_MULTIVALUED_WRITES` (I dont really now what they do), the problem disappears.

**Comment by zardus** [comment]
`AVOID_MULTIVALUED_READS` and `AVOID_MULTIVALUED_WRITES` cause angr to, instead of carrying out symbolic reads or rights, return fresh symbolic variables. My guess for what's going on is the following:

Claripy currently processes ASTs recursively (easier to write), so very complex ASTs will cause recursion errors in Python. I am pretty sure that this is what's happening here, rather than an actual endless loop. The `AVOID_MULTIVALUED_READS` and `AVOID_MULTIVALUED_WRITES` options just cause very tiny (but also not actually correct, as the relationships are lost) ASTs to be used instead, so this also avoids the core issue (though the result is wrong in this case). The correct solution is to do one (or both) of two things:

1. Build in some functionality in angr to create a new symbolic variable to represent ASTs that get to a depth that's too big. This would have a similar effect, in this case, to the `AVOID_MULTIVALUED` options, but would maintain correctness. This could be done ad-hoc as a SimInspect hook, btw, similar to your simplifiers.
2. Look at the operation and see what can be simplified. Usually, an AST that hits the recursion limit is doing something dumb over and over again, and it can be optimized away. The place to put this in would be the simplification functions here: https://github.com/angr/claripy/blob/master/claripy/operations.py

Your simplifier looks pretty good, btw (based on a quick look!). I think it would be a great addition to Claripy, and should simplify a decent amount of ASTs in other situations as well. In general, I guess, there are a lot of places where we could improve our simplifications for `Reverse`. If you could add your simplification (and a testcase for it) to claripy, we would be very thankful!

**Comment by zardus** [comment]
Actually, I just noticed that a) this is in VSA (so the "fresh symbolic variable" stuff won't really be feasible) and the operation is union (which might be hard to simplify -- that's Fish's domain). We might need some VSA-specific fix.

In either case, that simplifier would be useful in Claripy!

**Comment by ltfish** [comment]
@zardus Your introduction of `AVOID_MULTIVALUED_READS` and `AVOID_MULTIVALUED_WRITES` should definitely go to the documentation.

**Comment by ltfish** [comment]
@axt zardus is correct in the sense that this issue is on me. It looks like a bug in claripy.

**Comment by zardus** [comment]
@ltfish, I added a reference to the options file (where there are comments on the options) in the simuvex angr-doc page. I started copying the comments into angr-doc, but having them duplicated is probably going to lead to a lot of headache.

**Comment by axt** [comment]
@zardus Tried to run `test_simplify.py' in claripy, and get this error:
```
claripy.errors.BackendError: Unknown Z3 error in abstraction (result_ty == 'UNINTERPRETED'). Update your version of Z3, and, if the problem persists, open a claripy issue.
```
My Z3 version is theoretically the latest from angr-z3:
```
Installed /usr/local/lib/python2.7/dist-packages/angr_only_z3_custom-4.4.1.post4-py2.7.egg
```
Do you have any ideas how to resolve this error?


@ltfish:  @zardus is right, the AST is not infinite, probably just large and I think this is the responsibe code for it:
`simuvex/simuvex/plugins/abstract_memory.py`                                                                                                           
```
    def _load(self, addr, size, condition=None, fallback=None):
        address_wrappers = self.normalize_address(addr, is_write=False)

        [...]        
        if len(address_wrappers) > 1 and AVOID_MULTIVALUED_READS in self.state.options:
            val = self.state.se.Unconstrained('unconstrained_read', size * 8)
            return address_wrappers, val, [True]

        for aw in address_wrappers:
            new_val = self._do_load(aw.address, size, aw.region,
                                 is_stack=aw.is_on_stack, related_function_addr=aw.function_address)

            if val is None:
                if KEEP_MEMORY_READS_DISCRETE in self.state.options:
                    val = self.state.se.DSIS(to_conv=new_val, max_card=100000)
                else:
                    val = new_val
            else:
                val = val.union(new_val)
        
        return address_wrappers, val, [True]
```

**Comment by axt** [comment]
@zardus Nevermind, it had just a conflict with another Z3 install. I should have used a virtualenv I guess.

**Comment by axt** [comment]
@zardus I'm a bit lost here!

If I run the following code:
```
print claripy.backends.z3.simplify(
    claripy.Reverse(claripy.Extract(31,16,claripy.Reverse(claripy.BVS('x',32)))))
```

Then it will print out this result:
```
<BV16 x_3_32[15:0]>
```
Which is correct, **so this kind of simplification is already in claripy**.

But if I run the following code:
```
    """
	0x0:	push	ebp
	0x1:	mov	ebp, esp
	0x3:	movsx	esi, word ptr [ebp + 8]
	0x7:	cmp	si, 0x7f
	0xb:	jg	0x24
    """
    code = "\x55\x89\xe5\x0f\xbf\x75\x08\x66\x83\xfe\x7f\x7f\x17"
    proj = angr.Project(io.BytesIO(code), load_options={'main_opts': {'custom_arch':'x86'}})
    block = proj.factory.block(0x0)
    state = proj.factory.blank_state(addr=0x0, add_options={o.AVOID_MULTIVALUED_READS, o.AVOID_MULTIVALUED_WRITES, o.USE_SIMPLIFIED_CCALLS, o.SIMPLIFY_EXIT_GUARD})
    state.memory.store(state.regs.esp+ 4, claripy.BVS('arg0', proj.arch.bits), endness=proj.arch.memory_endness, inspect=False)
    simrun  = proj.factory.sim_run(state)
    print simrun.default_exit_guard

```
It leads to this:
```
<Bool Reverse(Reverse(arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:15] .. arg0_0_32[15:0])[31:16]) >s 0x7f>
```

But if I add my "read_consolidation" code to the initial state, then the result changes to this:
```
<Bool arg0_0_32[15:0] >s 0x7f>
```

**Comment by zardus** [comment]
Could you post the output to `ast.dbg_repr()` for those ASTs, without using Z3 simplification? The Z3 simplification does a lot of magic voodoo that is hard to keep track of :-)

**Comment by axt** [comment]
Sure, but which ones do you mean?

**Comment by zardus** [comment]
The first one (before passing it through z3.simplify) and the second one (the "it leads to this" AST).

**Comment by axt** [comment]
First one:
```
<BV Reverse (<BV Extract (31, 16, <BV Reverse (<BV BVS ('x_0_32', None, None, None, False, False, None)>)>)>)>
```

Second one:
Without the `read_consolidation` code:
```
<Bool SGT (<BV Reverse (<BV Extract (31, 16, <BV Reverse (<BV Concat (<BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 15, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV Extract (15, 0, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>)>)>)>)>, <BV BVV (127, 16)>)>
```
With `read_consolidation`:
```
<Bool SGT (<BV Extract (15L, 0L, <BV BVS ('arg0_0_32', None, None, None, False, False, None)>)>, <BV BVV (127, 16)>)>
```

Or the whole thing in a more readable (at least for me) form: http://pastebin.com/aZ346q1x

**Comment by axt** [comment]
So what I found strange, is that while backend_z3, knows how to simplify the Reverse(Extract(Reverse(...))) pattern, the exit guard doesn't gets simplified, although I used the SIMPLIFY_EXIT_GUARD option.

**Comment by zardus** [comment]
Yeah, that is really weird. The simplification should happen right here: https://git.seclab.cs.ucsb.edu/angr/simuvex/blob/master/simuvex/s_run.py#L88

Actually, I just realized that this simplification only happens in the successor that's added, not in the guard that's recorded. We should really move the simplification back to the conditional and default exit handlers, so that the SimIRSB saves them in the same way that they're applied to the successors.

So it looks like we *don't* have those Reverse(Extract(Reverse))) simplifications in Claripy, judging from the AST printouts. Z3 simplifies them, of course, but that's a bit slower. So the solutions, as I see them:

- your read consolidation trick
- adding real simplifiers in claripy
- adding the other simplification options (`SIMPLIFY_MEMORY_READS` might help for this, although it should already have been simplified on write....)

**Comment by axt** [comment]
I did my read consolidation trick, because it was much easier to do than to patch claripy. 

I think adding the real simplifier to claripy is a much cleaner solution, and with your hints it was easy to do it. I've sent a pull request, please have a look on it. (Note: I also renamed `boolean_reverse_simplifier` to `reverse_simplifier` because i think the boolean part of the name was just a copy-paste typo.)

My only problem is that I couldn't add a testcase, because I could't figure out, how to trigger the simplification mechanism, without including Z3 simplification in it. Although I tested it with my complex test I posted above, and it seems working.

**Comment by zardus** [comment]
Thanks! I moved the simplifier discussion to the MR. We can keep this issue for the VSA-specific stuff :-)
