### ISSUE TITLE
How t programmatically add constraints?

### ISSUE THREAD

**Issue by frapik99** [angr/claripy#27]
Hi all,
let's supposed i have created the 2 claripy.BV() objects called A and B. Supposed that as a parameter I receive O that is just the operation. Is it possible to do something like:

s.add(A O B)

so if O is < s.add(A< B) will be added instead if O is > s.add(A > B) would added?

So, I do need to specify the operation at runtime but I would not use if in the code.

Thanks

**Comment by zardus** [comment]
I'm not sure I follow... Is something like the `operator` module (https://docs.python.org/2/library/operator.html) what you're looking for?

**Comment by frapik99** [comment]
@zardus perfect thanks! I solved using operator.

Thanks
