### ISSUE TITLE
How to use extra_constraints

### ISSUE THREAD

**Issue by frapik99** [angr/claripy#28]
Hi,
thanks in advance for your help:

my code is the following:
```
import claripy
s = claripy.Solver()
x = claripy.BVS("x",64)
ten = claripy.BVV(10,64)
s.add(x==ten)
print s.satisfiable()
print s.satisfiable(extra_constraints=(x == 2))
```

The first satisfiable returns True as expected but for the second I have the following error:

```
Traceback (most recent call last):
  File "a.py", line 12, in <module>
    print s.satisfiable(extra_constraints=(x == 2))
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 30, in satisfiable
    ec = self._constraint_filter(extra_constraints)
  File "/usr/local/lib/python2.7/dist-packages/claripy/frontend_mixins/constraint_filter_mixin.py", line 3, in _constraint_filter
    if len(constraints) == 0:
TypeError: object of type 'Bool' has no len()
```

Could you tell me how to add properly that kind of extra constraint?

Thanks

**Comment by zardus** [comment]
You're passing a scalar value to `extra_constraints`, but it should be an iterable. Try this:

```print s.satisfiable(extra_constraints=(x == 2,))```

**Comment by frapik99** [comment]
It works! If possible I would suggest to improve the error message that is returned.

Thanks a lot

**Comment by zardus** [comment]
Just so I don't look like an unresponsive bum, I'm stating for the record that did end up improving the error message in https://github.com/angr/claripy/commit/905f20732e66ca366e13aed77ae9d1b25562dd39
