### ISSUE TITLE
Claripy needs concrete floats implemented with something other than python doubles

### ISSUE THREAD

**Issue by Justin-Ahn** [angr/claripy#280]
So correct me if I'm wrong here, but I've been looking at the solver tutorials/documentation, and I came across this: 
"If you want to specify the rounding mode for an operation, use the fp operation explicitly (solver.fpAdd for example) with a rounding mode (one of solver.fp.RM_*) as the first argument."

However, looking at the code itself for fpAdd, fpSub, etc., it doesn't look like the solvers actually support any rounding modes.
For example, if I try fpAdd w/ RTZ on two floating points, I will still get back an un-truncated float. 

Am I using this incorrectly or is this an issue?

Thanks.

**Comment by zwimer** [comment]
A note: eventually the C++ backend should (currently does but claricpp is not finished) support native 32-bit.
