### ISSUE TITLE
Use claripy on ARM

### ISSUE THREAD

**Issue by frapik99** [angr/claripy#29]
Hi,
I have installed angr using PIP on my tablet but when I try to import it I have an error at the instruction:

```
cannot import z3core
```

Can someone help me to fix it please? I have installed angr-z3 manually compiling the code...

Thanks

**Comment by frapik99** [comment]
Hi,
I solved copying build/python/z3 in my project's directory. Can something else to be done to avoid it?

Thanks

**Comment by ltfish** [comment]
I'm surprised that claripy (together with Z3) works on ARM...

I think it's a matter of providing the correct Z3path on your platform so claripy can find Z3 libraries automatically. See the top 63 lines in [claripy/backend_z3.py](https://github.com/angr/claripy/blob/master/claripy/backends/backend_z3.py). I don't have access to any ARM tablet that I can install claripy on. It'll be great if you can tell us where Z3 is installed to on your tablet!

**Comment by frapik99** [comment]
@ltfish Thanks for your answer. I'm able to install claripy and z3 on my ARM bu unfortunately VEX is not supported. Can I extract the information you need in a specific way?

Should I open an issue on PYVEX repo and understand if I can use it on ARM?

**Comment by ltfish** [comment]
I'm curious, does Valgrind support ARM as a host architecture?

I believe we can have VEX working on ARM no matter what as we only use it as a lifter.

**Comment by rhelmot** [comment]
Of course valgrind supports ARM as a host architecture!

There was an issue opened on PyVex a few days ago about this and I talked a
little about it there. It's ultimately just a bunch of debugging that has
to be done to iron out all the kinks.

**Comment by frapik99** [comment]
@rhelmot @ltfish I managed to install claripy on my ARM tablet. I'll try to create some example and share with you all the results. If you want me to try something in specific please let me know.

**Comment by frapik99** [comment]
I was able to use claripy on ARM. I can close this and discuss about ARM support for PyVEX on the other repo.

Thanks

**Comment by ltfish** [comment]
It'll be great if you can post your gotchas and examples somewhere, and we'll link them or include them in angr-doc!
