### ISSUE TITLE
Deprecation warning for `__truediv__` for `BV`s

### ISSUE THREAD

**Issue by zwimer** [angr/claripy#308]
### Description

We currently support the syntax `a / b` for `BV`s, but we do *not* do true division, we do floor division; i.e. `a // b`.

We should mark the `__truediv__` op for `BV`s as deprecated. It can continue to be supported, but it should be marked as deprecated and possibly print a deprecation warning.

**Comment by zwimer** [comment]
@ltfish Thoughts?

**Comment by ltfish** [comment]
LGTM. PR please?

**Comment by zwimer** [comment]
@ltfish Sure; how would you prefer a deprecation warning? `import warnings; warnings.DeprecationWarning`? Or I can just print a message to the logger `l.warning`. Normally I'd do the former but I know `angr` has its own warning system so I'm not sure if there is pushback against using `warnings` in `claripy`

**Comment by zwimer** [comment]
`warnings.warn` should already do that 'only once' thing, so I'll skip that.

**Comment by twizmwazin** [comment]
That decorator used to use a print instead of a real warning message, so we can probably simplify that function is python's warning system already does the right thing
