### ISSUE TITLE
Add check for unicode string value in BVV

### ISSUE THREAD

**Issue by ekilmer** [angr/claripy#32]
I was playing around and ran into some trouble while processing a unicode string at [1]. It's not too hard to handle a unicode string here. Obtaining the correct byte length for multi-byte unicode characters should still work with `len` on unicode strings. It should also return the correct hex encoded representation.

However, I haven't checked elsewhere for similar issues. Would the better solution be to create a hex string in my program before passing it in? Ex: '\xc3\xab\xcc\x81a\xc3\xba' instead of 'ë́aú'

I can submit a pull-request if you'd like the change that handles unicode.

Thank you!

[1] https://github.com/angr/claripy/blob/master/claripy/ast/bv.py#L182

**Comment by zardus** [comment]
I think having claripy handle unicode automatically could lead to confusion (for example, with copy-pasted string literals that are expected to be ascii but accidentally include some unicode character). I wouldn't be against a PR trying it out by decoding it to a string (and maybe logging a warning or something?).

**Comment by ltfish** [comment]
A thought for the future: does moving to Python 3 automatically solve this problem for us?

**Comment by rhelmot** [comment]
is this resolved now that #33 is merged or are there lingering design issues?

**Comment by ekilmer** [comment]
I haven't run into any other errors or problems with unicode since it was merged, so yeah I would say this is resolved.
