### ISSUE TITLE
OverflowError: long int too large to convert to int

### ISSUE THREAD

**Issue by frapik99** [angr/claripy#34]
Hi,
while creating the ```CFG``` for pngpixel ( see attached ) I have the following error:

my code is something like:
```
pngpixel = angr.Project(filename, load_options={'skip_libs': ['libpng12.so.0.54.0', 'libz.so.1.2.8'],'auto_load_libs': True})
...
self._cfg = self.project.analyses.CFGAccurate(context_sensitivity_level=1, keep_state=True)
```

```
line 201, in BVV
    value &= (1 << size) -1
OverflowError: long int too large to convert to int
[pngpixel.zip](https://github.com/angr/claripy/files/802210/pngpixel.zip)

```

I'm using the latest version of ```claripy```

I hope this can help to fix this issue. Happy to retest the fix once applied.

Thanks

**Comment by zardus** [comment]
@ltfish, could you look into this when you have some time? Let me know if it's actually a Claripy issue...

**Comment by ltfish** [comment]
@zardus You know how busy I am and I won't be able to handle it before iCTF.

**Comment by zardus** [comment]
Of course. I'm surprised you even responded so fast :-)
