### ISSUE TITLE
Small bug in replacement solver

### ISSUE THREAD

**Issue by jarsp** [angr/claripy#48]
I believe [Line 82 of replacement_frontend.py](https://github.com/angr/claripy/blob/master/claripy/frontends/replacement_frontend.py#L82) incorrectly iterates over the `self._replacements` dictionary:

Original:
```self._replacements = {k: v for k, v in self._replacements if k not in old_entries}```

Probably intended behavior:
```self._replacements = {k: v for k, v in self._replacements.iteritems() if k not in old_entries}```

The current code will throw an exception on use (so I'm guessing it's not actually being used?).

**Comment by ltfish** [comment]
It looks to me that you are absolutely right. @zardus ?

**Comment by zardus** [comment]
Agreed...

**Comment by zardus** [comment]
Closed by commit 141d4f7
