### ISSUE TITLE
Claripy not respecting max

### ISSUE THREAD

**Issue by palkeo** [angr/claripy#50]
I found something that's either a bug, or the documentation needs to be updated:

```
import claripy

a = claripy.BVS('test', 8, max=42)
s = claripy.Solver()
s.max(a)
```
Excpected: 42. Actual: 255.
The max is also not respected if I add a conflicting constraint and use eval().

**Comment by zardus** [comment]
This could be documented somewhere, but at the moment, the `max`, `min`, and `stride` arguments to a BVS only affect results when using VSA. I haven't found a non-ugly way to have them automatically apply when using the symbolic domain.

Some ideas, for the record:

1. Use an ITE: `claripy.BVS('test', 8, max=42)` would become `If(test > 8, 8, test)`, with similar things for min and stride. This seems super ugly.
2. Have solvers automatically add these sorts of "implicit" constraints when you attempt to evaluate an expression (temporarily, via `extra_constraints`) or when you add an expression as part of a constraint (permanently). This seems a bit too magical, but is probably the better solution.

**Comment by ltfish** [comment]
I like the second idea much better.

**Comment by palkeo** [comment]
I had the feeling that it was supported previously, and apparently it was:
https://github.com/angr/claripy/commit/2007a77e07581348f58060b56b6e7274600f31a9#diff-47381733fd308a0912809f3b99e8fb1c

What's the reason for it to be commented? Could it be safely un-commented?

**Comment by zardus** [comment]
I'll be 100% honest with you: I have absolutely no memory of that code... Apparently I *did* implement `#1`...

Naturally, I also have no memory of why I commented it out. Go ahead and give it a try! If nothing blows up, then we can probably put it back in.

**Comment by palkeo** [comment]
That's a bit awkward: Everywhere else we make the distinction between signed and unsigned comparison. Here, min and max implicitly have to choose.

**Comment by zardus** [comment]
Yeah, it's due to VSA -- those bounds are signed. We _could_ segregate the signed and unsigned bounds, but VSA wouldn't support the latter.

@ltfish, any musings on this? Should we add a "help wanted" project to add an unsigned mode to VSA for someone crazy enough to do it?

**Comment by saullocarvalho** [comment]
Is this still an issue? What can I do to help?

**Comment by rhelmot** [comment]
The conclusion we came to in the meantime is that we should _absolutely not_ allow uses of the min/max/stride BVS properties outside of VSA. My preference would be that strided interval ASTs were not piggybacked on BVS at all, but that'll be a pretty serious refactor.
