### ISSUE TITLE
FP.isNaN() and FP.isInf() broken for FPV

### ISSUE THREAD

**Issue by antifob** [angr/claripy#571]
### Description

Thanks for the project. :)

For `FP.isNaN()` and `FP.isInf()` on FPVs, the concrete backend is used. The code ends up at Python's `math.isnan(x)` and `math.isinf(x)`methods, respectively, where `x` is the FP. This call causes a `TypeError` exception.

### Steps to reproduce the bug

```
from claripy import FPS, FPV, FSORT_FLOAT

s = FPS('s', FSORT_FLOAT)
s.isNaN() # okay
s.isInf() # okay

v = FPV(0, FSORT_FLOAT)
v.isNaN() # TypeError
v.isNaN() # TypeError
```

The FPV first needs to be "solved", but maybe there's another workaround?

```
import math
from claripy import FPV, FSORT_FLOAT, Solver

nan = FPV(math.nan, FSORT_FLOAT)
nan.isNaN() # TypeError

inf = FPV(math.inf, FSORT_FLOAT)
inf.isInf() # TypeError

slv = Solver()
math.isnan(slv.eval(nan, 1)[0]) # True
math.isinf(slv.eval(inf, 1)[0]) # True
```

### Environment

```
claripy==9.2.128
```

**Comment by antifob** [comment]
Wow, that was quick! Thanks! :tada:  lgtm

**Comment by twizmwazin** [comment]
No problem, thanks for the report!
