### ISSUE TITLE
Logic error in claripy z3 min function

### ISSUE THREAD

**Issue by Tim-Nosco** [angr/claripy#76]
Located [here](https://github.com/angr/claripy/blob/master/claripy/backends/backend_z3.py#L687).
The return statement causes `extra_constraints` to not be removed from the z3 solver.

Also, consider using the z3 [optimize](https://z3prover.github.io/api/html/classz3py_1_1_optimize.html) object as it works quite well and will probably out perform your multiple evals.

**Comment by ltfish** [comment]
It seems to be a real bug to me! Assigning it to @zardus.
