### ISSUE TITLE
VSA .add() API inconsistent

### ISSUE THREAD

**Issue by axt** [angr/claripy#8]
We discussed this somewhat on irc some weeks ago.

This is the test code:

```python
sv = claripy.FullFrontend(claripy.backends.z3)
x = claripy.BVS('x', 32)
sv.add(x < 50000) 
sv.add(x < 30000) 
sv.add(x > 20000)
print sv.max(x),"-",sv.min(x)

sv = claripy.FullFrontend(claripy.backends.z3)
x = claripy.BVS('x', 32)
sv.add([x < 50000, x < 30000, x > 20000])
print sv.max(x),"-",sv.min(x)
```
Which yields the following (correct) results:
```
29999 - 20001
29999 - 20001
```

If I replace the solver to vsa:
```python
sv = claripy.ReplacementFrontend(claripy.LightFrontend(claripy.backends.vsa), replace_constraints=True, complex_auto_replace=True)
x = claripy.BVS('x', 32)
sv.add(x < 50000) 
sv.add(x < 30000) 
sv.add(x > 20000)
print sv.max(x),"-",sv.min(x)

sv = claripy.ReplacementFrontend(claripy.LightFrontend(claripy.backends.vsa), replace_constraints=True, complex_auto_replace=True)
x = claripy.BVS('x', 32)
sv.add([x < 50000, x < 30000, x > 20000])
print sv.max(x),"-",sv.min(x)
```

Yields the following:
```
49999 - 0
29999 - 19999
```
It seems, that VSA only uses the first specified constraint (first `add` call), when calculating its result.
[This seems inconsistent with the functionality of `add` function if the backend is set to Z3.]

If we specify all the constraints in one `add` call, then it works, but it miscalculates the UGT(>) expression (probably when inverting it).

**Comment by zardus** [comment]
Sorry to keep you hanging so long. This is a known issue with the ReplacementFrontend, specifically with line 181 (https://github.com/angr/claripy/blob/master/claripy/frontends/replacement_frontend.py#L181). Some improvements to the underlying AST replacement support are required to make this work properly.

**Comment by axt** [comment]
Thanks. Actually it doesn't bother me, just reported it, to notify you guys about it. 
Feel free to close the ticket.

**Comment by axt** [comment]
It seems solved with the new version. The case can be closed.

Only a sidenote: The `add` function iterates over the given constraints while processing them.
```
sv.add([x<1000,x>200])
```

If I call it like this:
```
sv.add(x<1000)
``` 
then it will throw `ClaripyOperationError("Please don't iterate over, or split, AST nodes!")` because it tries to iterate over the supplied ast object. 

What do you think about checking if the parameter is a list, and 
- throwing an exception immediatelly  (if the above format is not supposed to be supported)
- not doing the iteration, if the above format is supposed to be supported

**Comment by zardus** [comment]
Hmm, weird... The AddListMixin is supposed to take care of that... Are you building a custom solver or using one of the ones in solvers.py?

**Comment by axt** [comment]
I've used this old-style construct
```
sv = claripy.frontends.FullFrontend(claripy.backends.z3)
```
I see now that I should use one of the constructs, from `solver.py`.

Thanks. I'm closing the issue!
