### ISSUE TITLE
Document the relation between AST/Frontend/FrontendMixin/Backend

### ISSUE THREAD

**Issue by ltfish** [angr/claripy#84]
The following is quoted from @zardus in the Slack channel. We should put them in the documentation.

generally speaking:
- claripy abstracts expressions using `claripy.AST` objects
- `Frontend`s provide different paradigms for handling those expressions. The `FullFrontend` (should really be named `SolverFrontend` or something) handles them using something like an SMT solver, `LightFrontend` (should really be named `ApproximationFrontend` or something) handles them by using an abstract (and approximating) data domain.
- each `Frontend` needs to, at some point, do actual operation and evaluations on the `AST`. `AST`s don't support this on their own. Instead, `Backend`s translate `AST`s into `BackendObject`s (i.e., python primitives, Z3 expressions, strided intervals for VSA, etc) and also handle the appropriate state-tracking objects (such as Z3 solvers)
- `Frontend`s take `AST`s as inputs and use `Backend`s to `backend.convert()` those `AST`s into `BackendObjects` that can be evaluated and otherwise reasoned about
- `FrontendMixin`s customize the operation of `Frontend`s. For example, `ModelCacheMixin` caches solutions from an SMT solver

**Comment by zardus** [comment]
Done yesterday :-)

https://github.com/angr/angr-doc/commit/043e50ad943beba7c98851313ff2f6542763834e

This might be a good use-case for some sort of diagram.

**Comment by ltfish** [comment]
Awesome!
