### ISSUE TITLE
Exposing solvers returning `unknown`

### ISSUE THREAD

**Issue by Lukas-Dresel** [angr/claripy#89]
So, @rhelmot , @zardus , @ltfish: we have an interesting dilemma on our hands now where we implemented a portfolio frontend dishing the constraints out to multiple different solvers and returning the first answers received by any of the solvers. 

However, some solvers, e.g. CVC4, return `unknown` almost immediately for some constraints they can't deal with. This means we now need to be able to differentiate between `unknown`, `unsat` and `sat` results returned from solvers in order to only accept answers in the portfolio that are certain. What do you think is the best way to deal with this?

**Comment by rhelmot** [comment]
Implement unknown as an exception the same way as I got halfway through
doing in order to support timeouts better?

**Comment by Lukas-Dresel** [comment]
We have the following ideas to deal with this issue: 

- Expose a function, I'll call it `check_satisfiability` for now, that actually returns the solver response as it is received, so `'SAT'`, `'UNSAT'` or `'UNKNOWN'`
- Throw a `ResultUnknown` exception
- Make `satisfiable` return None in the case of `unknown`, this would still evaluate to False

Right now I think this list is in the order of our presence as we think what the cleanest solutions are.

**Comment by rhelmot** [comment]
We already have a function, it's called `satisfiable()`. We can just make it return members of an enum who we override the `__nonzero__` such that SAT is truthy and the rest are falsey. I like that idea the best.

**Comment by zardus** [comment]
I agree with @rhelmot. Let's go for an enum, with only SAT being truthy. If we also override `__eq__` to evaluate to z3.sat and "sat" as well, then I think we'll have a nice universal solution.

**Comment by rhelmot** [comment]
This is now solved as of #285 - there are multiple kinds of unknowns, each of which gets a different kind of exception raised for them.
